import Book from '../assets/book.png'
import Travel from '../assets/travel_2.png'
import Travel2 from '../assets/travel.png'
import Editor from '../assets/editor.png'
import Influencer from '../assets/influencer.png'

export const ListBlogs = [
    {
        id: 1,
        title: "The Ultimate Travel Guide: Top Destinations for Adventure Seekers",
        description: "Embark on an exhilarating journey as we explore the most thrilling destinations around the world for adventure seekers. From scaling majestic mountains to diving into the depths of the ocean, this blog post will provide a comprehensive guide to adrenaline-pumping activities and breathtaking landscapes. Discover hidden gems, adrenaline-fueled experiences, and insider tips for adventure travel enthusiasts looking to push their boundaries and create unforgettable memories.",
        image: Book,
        userCreated: 'User 1',
        datePosted: 'May 1, 2023',
        numReviews: 10,
        numViews: 100,
        tag: "Travel",
        userImage:Editor,
    },
    {
        id: 2,
        title: "The Role of Education in Shaping the Future Generation",
        description: "Education is the foundation of a prosperous society. In this blog post, we will delve into the critical role education plays in shaping the minds of the future generation. Explore how education fosters intellectual growth, cultivates essential skills, and instills values that prepare individuals for success in a rapidly evolving world. Discuss the significance of innovative teaching methods, inclusive education, and lifelong learning in equipping the next generation with the tools they need to navigate the challenges and seize the opportunities of the future.",
        image: Travel2,
        userCreated: 'User 2',
        datePosted: 'May 2, 2023',
        numReviews: 5,
        numViews: 50,
        tag: "Education",
        userImage:Editor,
    },
    {
        id: 3,
        title: "Social Media: The Good, the Bad, and the Impact on Society",
        description: "Step into the captivating world of social media and examine its profound influence on individuals and society as a whole. This blog post will delve into the positive aspects of social media, such as its power to connect people, amplify voices, and drive social change. It will also address the negative impacts, including the effects on mental health, privacy concerns, and the spread of misinformation. Analyze the evolving role of social media in shaping societal norms, political landscapes, and cultural trends, and explore strategies for cultivating a healthy and responsible digital presence",
        image: Travel,
        userCreated: 'User 2',
        datePosted: 'May 2, 2023',
        numReviews: 5,
        numViews: 50,
        userImage:Editor,
    },
    {
        id: 4,
        title: "The Ultimate Travel Guide: Top Destinations for Adventure Seekers",
        description: "Embark on an exhilarating journey as we explore the most thrilling destinations around the world for adventure seekers. From scaling majestic mountains to diving into the depths of the ocean, this blog post will provide a comprehensive guide to adrenaline-pumping activities and breathtaking landscapes. Discover hidden gems, adrenaline-fueled experiences, and insider tips for adventure travel enthusiasts looking to push their boundaries and create unforgettable memories.",
        image: Editor,
        userCreated: 'User 2',
        datePosted: 'May 2, 2023',
        numReviews: 5,
        numViews: 50,
        tag: "Travel",
        userImage:Editor,
    },
    {
        id: 5,
        title: "The Role of Education in Shaping the Future Generation",
        description: "Education is the foundation of a prosperous society. In this blog post, we will delve into the critical role education plays in shaping the minds of the future generation. Explore how education fosters intellectual growth, cultivates essential skills, and instills values that prepare individuals for success in a rapidly evolving world. Discuss the significance of innovative teaching methods, inclusive education, and lifelong learning in equipping the next generation with the tools they need to navigate the challenges and seize the opportunities of the future.",
        image: Travel2,
        userCreated: 'User 2',
        datePosted: 'May 2, 2023',
        numReviews: 5,
        numViews: 50,
        tag: "Education",
        userImage:Editor,
    },
    {
        id: 6,
        title: "Social Media: The Good, the Bad, and the Impact on Society",
        description: "Step into the captivating world of social media and examine its profound influence on individuals and society as a whole. This blog post will delve into the positive aspects of social media, such as its power to connect people, amplify voices, and drive social change. It will also address the negative impacts, including the effects on mental health, privacy concerns, and the spread of misinformation. Analyze the evolving role of social media in shaping societal norms, political landscapes, and cultural trends, and explore strategies for cultivating a healthy and responsible digital presence",
        image: Influencer,
        userCreated: 'User 2',
        datePosted: 'May 2, 2023',
        numReviews: 5,
        numViews: 50,
        tag: "Social Media",
        userImage:Editor,
    },
]
export default ListBlogs